# -*- coding: utf-8 -*-
"""Crop_production.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16zeC-JRyj4rwUVQ3kp95BuvmoKzDqt9B

# **Crop recommendation system**

## 1. Load dataset
"""

import os
import pandas as pd
from sklearn.metrics import accuracy_score
def load_data():
    for p in ["Crop_Data.xlsx.csv", "Crop_recommendation.csv"]:
        if os.path.exists(p):
            return pd.read_csv(p)
        if os.path.exists(f"/mnt/data/{p}"):
            return pd.read_csv(f"/mnt/data/{p}")
    raise FileNotFoundError("Place your dataset as 'Crop_Data.xlsx.csv' or 'Crop_recommendation.csv' in the working directory.")

data = pd.read_csv("data/crop_recommendation.csv")
print("Columns in dataset:", data.columns)

"""## 2. Prepare Features and Target"""

target_col = 'label'
if target_col not in data.columns:
    raise ValueError(f"Target column '{target_col}' not found in dataset columns.")

X = data.drop(target_col, axis=1)
y = data[target_col]

print(f"Feature columns ({X.shape[1]}): {list(X.columns)}")

"""## 3️. Encode Target and Scale Features"""

from sklearn.preprocessing import LabelEncoder, StandardScaler

label_encoder = LabelEncoder()
y_encoded = label_encoder.fit_transform(y)

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

"""## 4. Handle Imbalanced Data (SMOTE)"""

from imblearn.over_sampling import SMOTE
import numpy as np
from sklearn.model_selection import train_test_split
smote = SMOTE(random_state=42)
# 5. Train-Test Split (BEFORE SMOTE)
X_train, X_test, y_train, y_test = train_test_split(
    X_scaled, y_encoded, test_size=0.2, random_state=42, stratify=y_encoded
)

# Apply SMOTE ONLY on training data
X_train, y_train = smote.fit_resample(X_train, y_train)

print(f"After SMOTE, training shape: {X_train.shape}")

"""## 5. Train-Test Split"""

from sklearn.model_selection import train_test_split

# Split first
X_train, X_test, y_train, y_test = train_test_split(
    X_scaled, y_encoded, test_size=0.2, random_state=42, stratify=y_encoded
)

# Apply SMOTE only on training
X_train, y_train = smote.fit_resample(X_train, y_train)
print(f"Train shape: {X_train.shape}, Test shape: {X_test.shape}")

from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier

# Split
X_train, X_test, y_train, y_test = train_test_split(
    X_scaled, y_encoded, test_size=0.2, random_state=42, stratify=y_encoded
)

# ===== BASELINE (NO SMOTE) =====
baseline_model = DecisionTreeClassifier(random_state=42)
baseline_model.fit(X_train, y_train)

baseline_pred = baseline_model.predict(X_test)
baseline_acc = accuracy_score(y_test, baseline_pred)

print(f"Baseline Accuracy: {baseline_acc * 100:.2f}%")

# ===== APPLY SMOTE ONLY FOR OPTIMIZED MODEL =====
X_train_smote, y_train_smote = smote.fit_resample(X_train, y_train)
from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import RandomForestClassifier

param_grid = {
    'n_estimators': [100, 200],
    'max_depth': [10, 20, None],
    'min_samples_leaf': [1, 2]
}

rf = RandomForestClassifier(class_weight='balanced', random_state=42)

grid_search = GridSearchCV(
    rf,
    param_grid,
    cv=5,
    n_jobs=-1,
    scoring='accuracy',
    verbose=2
)
# ===== OPTIMIZED MODEL =====
grid_search.fit(X_train_smote, y_train_smote)
best_model = grid_search.best_estimator_

y_pred = best_model.predict(X_test)
optimized_acc = accuracy_score(y_test, y_pred)

print(f"Optimized Accuracy: {optimized_acc * 100:.2f}%")

# ===== COMPARISON =====
print("\n=== Model Comparison ===")
print(f"Baseline Accuracy: {baseline_acc * 100:.2f}%")
print(f"Optimized Accuracy: {optimized_acc * 100:.2f}%")
print(f"Improvement: {(optimized_acc - baseline_acc) * 100:.2f}%")

if optimized_acc > baseline_acc:
    print("Model performance improved using SMOTE and GridSearchCV ✅")
else:
    print("No improvement observed ❌")

"""## 6. Hyperparameter Tuning (Random Forest)"""

from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import GridSearchCV

param_grid = {
    'n_estimators': [100, 200],
    'max_depth': [10, 20, None],
    'min_samples_leaf': [1, 2]
}

rf = RandomForestClassifier(class_weight='balanced', random_state=42)
grid_search = GridSearchCV(rf, param_grid, cv=5, n_jobs=-1, scoring='accuracy', verbose=2)
grid_search.fit(X_train, y_train)

best_model = grid_search.best_estimator_
print("Best Hyperparameters:", grid_search.best_params_)

"""## 7. Model Evaluation"""

from sklearn.metrics import classification_report, accuracy_score

# === Optimized Model Evaluation ===
y_pred = best_model.predict(X_test)
optimized_acc = accuracy_score(y_test, y_pred)

print(f"Optimized Accuracy: {optimized_acc * 100:.2f}%")

# === Accuracy Comparison ===
print("\n=== Model Comparison ===")
print(f"Baseline Accuracy: {baseline_acc * 100:.2f}%")
print(f"Optimized Accuracy: {optimized_acc * 100:.2f}%")
print(f"Improvement: {(optimized_acc - baseline_acc) * 100:.2f}%")

if optimized_acc > baseline_acc:
    print("Model performance improved using SMOTE and GridSearchCV ✅")
else:
    print("No improvement observed ❌")

print(classification_report(y_test, y_pred, target_names=label_encoder.classes_))

# === Accuracy Comparison Graph ===
import matplotlib.pyplot as plt

models = ['Baseline', 'Optimized']
accuracies = [baseline_acc * 100, optimized_acc * 100]

plt.figure(figsize=(6, 4))
plt.bar(models, accuracies)
plt.ylabel("Accuracy (%)")
plt.title("Model Performance Comparison")
plt.show()

"""## 8. Prepare DataFrames for SHAP"""

import pandas as pd

X_train_df = pd.DataFrame(X_train, columns=X.columns)
X_test_df = pd.DataFrame(X_test, columns=X.columns)

X_test_subset = X_test_df.sample(n=min(50, len(X_test_df)), random_state=42).reset_index(drop=True)

"""## 9. SHAP Explainer and Values"""

import shap
import numpy as np

explainer = shap.TreeExplainer(best_model)
shap_values = explainer.shap_values(X_test_subset)

print(f"SHAP values type: {type(shap_values)}")
if isinstance(shap_values, list):
    print(f"Multi-class with {len(shap_values)} classes")
    print(f"First class SHAP shape: {shap_values[0].shape}")
elif isinstance(shap_values, np.ndarray):
    print(f"SHAP values shape: {shap_values.shape}")
    if len(shap_values.shape) == 3:
        shap_values = [shap_values[:, :, i] for i in range(shap_values.shape[2])]
        print(f"Converted to list of {len(shap_values)} 2D arrays")

"""## 10. SHAP Summary Plot"""

import matplotlib.pyplot as plt
import numpy as np

try:
    if isinstance(shap_values, list):
        print("\nSHAP Feature Importance - Multi-Class Analysis")

        feature_names = list(X_test_subset.columns)
        n_features = len(feature_names)
        n_classes = len(label_encoder.classes_)

        shap_matrix = np.zeros((n_features, n_classes))
        for i in range(n_classes):
            shap_matrix[:, i] = np.mean(np.abs(shap_values[i]), axis=0)

        # --- Main stacked bar color palette (blue gradient) ---
        base_colors = [
            "#06141D", "#091822", "#0B1E28", "#112B3D", "#142F46", "#173550",
            "#1A3B5A", "#1D4064", "#20466E", "#234C78", "#275183", "#2A5790",
            "#2D5D9C", "#2F63A8", "#3269B4", "#366FC0", "#3975CC", "#3D7BD8",
            "#4181E4", "#4396F7", "#479DFB", "#4BA4FF"
        ]
        colors = [base_colors[i % len(base_colors)] for i in range(n_classes)]

        # --- Overall Feature Importance (stacked bars) ---
        plt.figure(figsize=(14, 10))
        bottom = np.zeros(n_features)

        for i in range(n_classes):
            class_name = label_encoder.classes_[i]
            plt.bar(
                feature_names,
                shap_matrix[:, i],
                bottom=bottom,
                color=colors[i],
                edgecolor="white",
                linewidth=0.5,
                alpha=0.95,
                label=f'{class_name}'
            )
            bottom += shap_matrix[:, i]

        plt.title('SHAP Feature Importance - All Classes', fontsize=20, fontweight='bold')
        plt.xlabel('Features', fontsize=20, fontweight="bold")
        plt.ylabel('Mean absolute SHAP value', fontsize=20, fontweight="bold")
        plt.xticks(rotation=45, ha='right', fontsize=20)
        plt.yticks(fontsize=16)
        plt.grid(axis='y', linestyle="--", alpha=0.6)
        plt.legend(loc='upper right', fontsize=15, frameon=True)
        plt.tight_layout()
        plt.show()

        # --- Top 3 Most Important Features ---
        print("\nTop 3 Most Important Features Analysis:")
        total_importance = np.sum(shap_matrix, axis=1)
        top_feature_indices = np.argsort(total_importance)[::-1][:3]

        # Different palettes for top-3 feature plots
        top3_palettes = [[
      "#D0F0F6", "#B0E1E3", "#90D2D0", "#70C3BD", "#50B4AA", "#30A497",
    "#109584", "#0E8571", "#0C745E", "#0A634B", "#085238", "#064125",
    "#053018", "#04200D", "#041503", "#3E0F00", "#7A1A00", "#B42500",
    "#E53000", "#FF3B00", "#FF4500", "#FF4F00"
],
           [
    "#FFC0CB", "#FFB3C0", "#FFA6B3", "#FF99A6", "#FF8C99", "#FF7F8C",
    "#FF7280", "#FF6573", "#FF5870", "#FF4B66", "#FF3E5C", "#FF3153",
    "#FF2449", "#FF173F", "#FF0A36", "#FF002D", "#F00028", "#E00023",
    "#D0001E", "#C00019", "#B00014", "#A0000F"
]  , [
    "#E0F2F1", "#C1E4E0", "#A3D6CF", "#85C9BF", "#67BBB0", "#4AAEA0",
    "#2C9F90", "#0F9180", "#0D7A6D", "#0B645A", "#094E47", "#073835",
    "#052322", "#051F1F", "#051B1B", "#041717", "#031313", "#020E0E",
    "#020A0A", "#010707", "#010303", "#000000", "#000000"
]
        ]

        for idx, palette in zip(top_feature_indices, top3_palettes):
            feature_name = feature_names[idx]
            print(f"\n{feature_name.upper()} - Total Importance: {total_importance[idx]:.4f}")

            plt.figure(figsize=(12, 8))
            feature_shap = shap_matrix[idx, :]
            class_names = label_encoder.classes_

            # Sort by SHAP value descending
            sorted_indices = np.argsort(feature_shap)[::-1]
            sorted_classes = [class_names[i] for i in sorted_indices]
            sorted_values = feature_shap[sorted_indices]

            # Use the palette for this top feature
            sorted_colors = [palette[i % len(palette)] for i in range(len(sorted_values))]

            bars = plt.bar(
                range(len(sorted_classes)),
                sorted_values,
                color=sorted_colors,
                edgecolor="white",
                linewidth=0.5,
                alpha=0.95
            )

            plt.title(f'SHAP Importance: {feature_name.upper()} across all classes',
                      fontsize=20, fontweight='bold')
            plt.xlabel('Classes', fontsize=20, fontweight="bold")
            plt.ylabel('Mean Absolute SHAP Value', fontsize=20, fontweight="bold")
            plt.xticks(range(len(sorted_classes)), sorted_classes, rotation=45, ha='right', fontsize=20)
            plt.yticks(fontsize=12)
            plt.grid(axis='y', linestyle="--", alpha=0.6)

            for bar, value in zip(bars, sorted_values):
                if value > 0.01:
                    plt.text(bar.get_x() + bar.get_width()/2,
                             bar.get_height() + 0.005,
                             f'{value:.3f}',
                             ha='center', va='bottom', fontsize=12, fontweight="bold")

            plt.tight_layout()
            plt.show()

    else:
        # --- Single-output case ---
        print("\nSHAP Summary Plot")
        plt.figure(figsize=(10, 8))
        mean_shap = np.mean(np.abs(shap_values), axis=0)
        feature_names = list(X_test_subset.columns)

        bars = plt.bar(
            feature_names,
            mean_shap,
            color="#0B1E28",
            edgecolor="white",
            linewidth=1.3,
            alpha=0.95
        )

        plt.title('SHAP Feature Importance', fontsize=20, fontweight='bold')
        plt.xlabel('Features', fontsize=20, fontweight="bold")
        plt.ylabel('Mean Absolute SHAP Value', fontsize=20, fontweight="bold")
        plt.xticks(rotation=45, ha='right', fontsize=15)
        plt.yticks(fontsize=12)
        plt.grid(axis='y', linestyle="--", alpha=0.6)

        for bar, value in zip(bars, mean_shap):
            if value > 0.01:
                plt.text(bar.get_x() + bar.get_width()/2,
                         bar.get_height() + 0.005,
                         f'{value:.3f}',
                         ha='center', va='bottom', fontsize=15, fontweight="bold")

        plt.tight_layout()
        plt.show()

except Exception as e:
    print(f"Error creating SHAP plots: {e}")
    print("Continuing without SHAP visualization...")

"""## 11. Feature Importance from Random Forest"""

import matplotlib.pyplot as plt

feature_importance = pd.DataFrame({
    'feature': X.columns,
    'importance': best_model.feature_importances_
}).sort_values('importance', ascending=False)

print("\nTop 10 Most Important Features:")
print(feature_importance.head(10))

plt.figure(figsize=(10, 8))
plt.bar(feature_importance.head(10)['feature'],
        feature_importance.head(10)['importance'],
        color='#04200D', alpha=0.7)

plt.title('Top 10 Feature Importance (Random Forest)')
plt.xlabel('Features')
plt.ylabel('Importance')
plt.xticks(rotation=45, ha='right')
plt.grid(axis='y', alpha=0.3)
plt.tight_layout()
plt.show()

"""## 1️2. Economic Impact Estimation Function"""

def estimate_economic_impact(crop_name, confidence_score, region_id=1):
    """
    Enhanced economic impact estimation based on confidence score and crop type
    """
    # Comprehensive crop economic data (profit increase percentages)
    base_impacts = {
        'rice': 18, 'wheat': 15, 'cotton': 22, 'sugarcane': 20,
        'maize': 16, 'jute': 12, 'coffee': 25, 'coconut': 14,
        'apple': 28, 'banana': 24, 'blackgram': 13, 'chickpea': 17,
        'grapes': 30, 'kidneybeans': 15, 'lentil': 14, 'mango': 26,
        'mothbeans': 11, 'mungbean': 13, 'muskmelon': 19, 'orange': 23,
        'papaya': 21, 'pigeonpeas': 12, 'pomegranate': 27, 'watermelon': 18
    }

    base_impact = base_impacts.get(crop_name.lower(), 10)

    # Adjust impact based on confidence score and add regional factors
    confidence_multiplier = confidence_score / 100
    regional_factor = 1.0 + (region_id * 0.05)  # 5% increase per region

    adjusted_impact = base_impact * confidence_multiplier * regional_factor

    # Determine risk level and market potential
    if confidence_score > 85:
        risk_level = 'Very Low'
        market_potential = 'Excellent'
    elif confidence_score > 70:
        risk_level = 'Low'
        market_potential = 'Good'
    elif confidence_score > 55:
        risk_level = 'Medium'
        market_potential = 'Fair'
    else:
        risk_level = 'High'
        market_potential = 'Poor'

    return {
        'crop': crop_name,
        'region': region_id,
        'estimated_profit_increase': f"{adjusted_impact:.1f}%",
        'base_profit_potential': f"{base_impact}%",
        'confidence': f"{confidence_score:.1f}%",
        'risk_level': risk_level,
        'market_potential': market_potential,
        'investment_recommendation': 'Highly Recommended' if confidence_score > 75 else 'Recommended' if confidence_score > 60 else 'Consider Alternatives'
    }
def get_unique_crop_recommendation(sensor_data_list):
    """
    Get unique crop recommendations for multiple sensor inputs
    Ensures no duplicate recommendations across different inputs
    """
    all_recommendations = []
    used_crops = set()

    for i, sensor_data in enumerate(sensor_data_list):
        result = predict_crop_with_confidence(sensor_data)

        # Find the best crop that hasn't been recommended yet
        unique_crop = None
        best_confidence = 0

        for rec in result['all_recommendations']:
            if rec['crop'] not in used_crops and rec['confidence'] > best_confidence:
                unique_crop = rec
                best_confidence = rec['confidence']

        if unique_crop:
            used_crops.add(unique_crop['crop'])
            all_recommendations.append({
                'input_id': i + 1,
                'sensor_data': sensor_data,
                'recommended_crop': unique_crop['crop'],
                'confidence': unique_crop['confidence'],
                'economic_impact': unique_crop['economic_impact']
            })
        else:
            # If no unique crop found, get the best available
            best_rec = result['all_recommendations'][0] if result['all_recommendations'] else None
            if best_rec:
                all_recommendations.append({
                    'input_id': i + 1,
                    'sensor_data': sensor_data,
                    'recommended_crop': best_rec['crop'] + ' (duplicate)',
                    'confidence': best_rec['confidence'],
                    'economic_impact': best_rec['economic_impact']
                })

    return all_recommendations

"""## 13. Enhanced Prediction with Confidence"""

import numpy as np
import pandas as pd

def predict_crop_with_confidence(sensor_data):
    input_df = pd.DataFrame([sensor_data])

    missing_cols = set(X.columns) - set(input_df.columns)
    if missing_cols:
        raise ValueError(f"Missing required columns: {missing_cols}")

    input_df = input_df[X.columns]
    input_scaled = scaler.transform(input_df)

    prediction = best_model.predict(input_scaled)
    probabilities = best_model.predict_proba(input_scaled)

    top_indices = np.argsort(probabilities[0])[::-1][:3]
    recommendations = []

    for idx in top_indices:
        crop_name = label_encoder.inverse_transform([idx])[0]
        confidence = probabilities[0][idx] * 100
        economic_impact = estimate_economic_impact(crop_name, confidence)

        recommendations.append({
            'crop': crop_name,
            'confidence': confidence,
            'economic_impact': economic_impact
        })

    return {
        'primary_recommendation': label_encoder.inverse_transform(prediction)[0],
        'all_recommendations': recommendations,
        'sensor_data': sensor_data
    }

"""## 1️4. Save Model and Preprocessors"""

import joblib

try:
    joblib.dump(best_model, 'adaptive_crop_recommender_model.pkl')
    joblib.dump(label_encoder, 'label_encoder.pkl')
    joblib.dump(scaler, 'scaler.pkl')
    joblib.dump(feature_importance, 'feature_importance.pkl')
    print("Models and preprocessors saved successfully!")
except Exception as e:
    print(f"Error saving models: {e}")

"""## 15. Real-Time Prediction Examples"""

# === 12️⃣ Economic Impact Analysis ===
def estimate_economic_impact(crop_name, confidence_score, region_id=1):
    """
    Enhanced economic impact estimation based on confidence score and crop type
    """
    # Comprehensive crop economic data (profit increase percentages)
    base_impacts = {
        'rice': 18, 'wheat': 15, 'cotton': 22, 'sugarcane': 20,
        'maize': 16, 'jute': 12, 'coffee': 25, 'coconut': 14,
        'apple': 28, 'banana': 24, 'blackgram': 13, 'chickpea': 17,
        'grapes': 30, 'kidneybeans': 15, 'lentil': 14, 'mango': 26,
        'mothbeans': 11, 'mungbean': 13, 'muskmelon': 19, 'orange': 23,
        'papaya': 21, 'pigeonpeas': 12, 'pomegranate': 27, 'watermelon': 18
    }

    base_impact = base_impacts.get(crop_name.lower(), 10)

    # Adjust impact based on confidence score and add regional factors
    confidence_multiplier = confidence_score / 100
    regional_factor = 1.0 + (region_id * 0.05)  # 5% increase per region

    adjusted_impact = base_impact * confidence_multiplier * regional_factor

    # Determine risk level and market potential
    if confidence_score > 85:
        risk_level = 'Very Low'
        market_potential = 'Excellent'
    elif confidence_score > 70:
        risk_level = 'Low'
        market_potential = 'Good'
    elif confidence_score > 55:
        risk_level = 'Medium'
        market_potential = 'Fair'
    else:
        risk_level = 'High'
        market_potential = 'Poor'

    return {
        'crop': crop_name,
        'region': region_id,
        'estimated_profit_increase': f"{adjusted_impact:.1f}%",
        'base_profit_potential': f"{base_impact}%",
        'confidence': f"{confidence_score:.1f}%",
        'risk_level': risk_level,
        'market_potential': market_potential,
        'investment_recommendation': 'Highly Recommended' if confidence_score > 75 else 'Recommended' if confidence_score > 60 else 'Consider Alternatives'
    }

# === 13️⃣ Enhanced Prediction Function ===
def predict_crop_with_confidence(sensor_data):
    """
    Enhanced prediction function that returns crop recommendation with confidence scores
    """
    input_df = pd.DataFrame([sensor_data])

    # Ensure all required columns are present
    missing_cols = set(X.columns) - set(input_df.columns)
    if missing_cols:
        raise ValueError(f"Missing required columns: {missing_cols}")

    # Reorder columns to match training features
    input_df = input_df[X.columns]
    input_scaled = scaler.transform(input_df)

    # Get prediction and probabilities
    prediction = best_model.predict(input_scaled)
    probabilities = best_model.predict_proba(input_scaled)

    # Get top 3 recommendations
    top_indices = np.argsort(probabilities[0])[::-1][:3]
    recommendations = []

    for idx in top_indices:
        crop_name = label_encoder.inverse_transform([idx])[0]
        confidence = probabilities[0][idx] * 100
        economic_impact = estimate_economic_impact(crop_name, confidence)

        recommendations.append({
            'crop': crop_name,
            'confidence': confidence,
            'economic_impact': economic_impact
        })

    return {
        'primary_recommendation': label_encoder.inverse_transform(prediction)[0],
        'all_recommendations': recommendations,
        'sensor_data': sensor_data,
        'unique_recommendation': recommendations[0]['crop'] if recommendations else 'No suitable crop found'
    }

# === 14️⃣ Unique Crop Recommendation Function ===
def get_unique_crop_recommendation(sensor_data_list):
    """
    Get unique crop recommendations for multiple sensor inputs
    Ensures no duplicate recommendations across different inputs
    """
    all_recommendations = []
    used_crops = set()

    for i, sensor_data in enumerate(sensor_data_list):
        result = predict_crop_with_confidence(sensor_data)

        # Find the best crop that hasn't been recommended yet
        unique_crop = None
        best_confidence = 0

        for rec in result['all_recommendations']:
            if rec['crop'] not in used_crops and rec['confidence'] > best_confidence:
                unique_crop = rec
                best_confidence = rec['confidence']

        if unique_crop:
            used_crops.add(unique_crop['crop'])
            all_recommendations.append({
                'input_id': i + 1,
                'sensor_data': sensor_data,
                'recommended_crop': unique_crop['crop'],
                'confidence': unique_crop['confidence'],
                'economic_impact': unique_crop['economic_impact']
            })
        else:
            # If no unique crop found, get the best available
            best_rec = result['all_recommendations'][0] if result['all_recommendations'] else None
            if best_rec:
                all_recommendations.append({
                    'input_id': i + 1,
                    'sensor_data': sensor_data,
                    'recommended_crop': best_rec['crop'] + ' (duplicate)',
                    'confidence': best_rec['confidence'],
                    'economic_impact': best_rec['economic_impact']
                })

    return all_recommendations
# === 15️⃣ Save Model and Preprocessing Objects ===
try:
    joblib.dump(best_model, 'adaptive_crop_recommender_model.pkl')
    joblib.dump(label_encoder, 'label_encoder.pkl')
    joblib.dump(scaler, 'scaler.pkl')
    joblib.dump(feature_importance, 'feature_importance.pkl')
    print("Models and preprocessors saved successfully!")
except Exception as e:
    print(f"Error saving models: {e}")

# === 16️⃣ Real-Time Prediction Examples ===
example_sensors = [
    {
        'N': 90, 'P': 42, 'K': 43, 'temperature': 25.5,
        'humidity': 70, 'ph': 6.8, 'rainfall': 150
    },
    {
        'N': 120, 'P': 60, 'K': 50, 'temperature': 22.0,
        'humidity': 65, 'ph': 7.2, 'rainfall': 80
    },
    {
        'N': 80, 'P': 35, 'K': 40, 'temperature': 28.0,
        'humidity': 75, 'ph': 6.5, 'rainfall': 200
    },
    {
        'N': 110, 'P': 55, 'K': 48, 'temperature': 30.0,
        'humidity': 80, 'ph': 7.0, 'rainfall': 120
    }
]

print("\n" + "="*50)
print("CROP RECOMMENDATION EXAMPLES")
print("="*50)

for i, sensor_data in enumerate(example_sensors, 1):
    try:
        result = predict_crop_with_confidence(sensor_data)
        print(f"\nExample {i}:")
        print(f"Sensor Data: {sensor_data}")
        print(f"Primary Recommendation: {result['primary_recommendation']}")
        print(f"Unique Recommendation: {result['unique_recommendation']}")
        print("\nTop 3 Recommendations:")
        for j, rec in enumerate(result['all_recommendations'], 1):
            econ = rec['economic_impact']
            print(f"  {j}. {rec['crop']} - Confidence: {rec['confidence']:.1f}%")
            print(f"     Economic Impact: {econ['estimated_profit_increase']} | Risk: {econ['risk_level']} | {econ['investment_recommendation']}")
    except Exception as e:
        print(f"Error in prediction {i}: {e}")

unique_recommendations = get_unique_crop_recommendation(example_sensors)
for rec in unique_recommendations:
    print(f"\nInput {rec['input_id']}:")
    print(f"Sensor Data: {rec['sensor_data']}")
    print(f"Unique Recommended Crop: {rec['recommended_crop']}")
    print(f"Confidence: {rec['confidence']:.1f}%")
    econ = rec['economic_impact']
    print(f"Economic Analysis:")
    print(f"  - Profit Increase: {econ['estimated_profit_increase']}")
    print(f"  - Risk Level: {econ['risk_level']}")
    print(f"  - Market Potential: {econ['market_potential']}")
    print(f"  - Investment Status: {econ['investment_recommendation']}")

"""## Economic Impact Analysis"""

# === 17️⃣ Unique Crop Recommendations Across Multiple Inputs ===
# === 18️⃣ Economic Impact Analysis Summary ===
print("\n" + "="*50)
print("ECONOMIC IMPACT ANALYSIS SUMMARY")
print("="*50)
print("\n" + "="*60)
# Test economic impact function with different scenarios
test_crops = ['rice', 'coffee', 'apple', 'cotton', 'mango']
test_confidences = [95, 85, 70, 60, 45]
print("UNIQUE CROP RECOMMENDATIONS FOR MULTIPLE INPUTS")
for crop, confidence in zip(test_crops, test_confidences):
    impact = estimate_economic_impact(crop, confidence, region_id=1)
    print(f"\n{crop.upper()} Analysis:")
    print(f"  Confidence Score: {impact['confidence']}")
    print(f"  Estimated Profit Increase: {impact['estimated_profit_increase']}")
    print(f"  Base Profit Potential: {impact['base_profit_potential']}")
    print(f"  Risk Level: {impact['risk_level']}")
    print(f"  Market Potential: {impact['market_potential']}")
    print(f"  Investment Recommendation: {impact['investment_recommendation']}")
print("="*60)

"""## 16. Model Performance Summary"""

print("\n" + "="*50)
print("MODEL PERFORMANCE SUMMARY")
print("="*50)

print(f"Final Model: {type(best_model).__name__}")
print(f"Best Parameters: {grid_search.best_params_}")
print(f"Cross-validation Score: {grid_search.best_score_:.4f}")
print(f"Test Accuracy: {accuracy_score(y_test, y_pred):.4f}")
print(f"Number of Classes: {len(label_encoder.classes_)}")
print(f"Classes: {list(label_encoder.classes_)}")
print(f"Dataset Shape: {data.shape}")
print(f"Features Used: {len(X.columns)}")

import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.ensemble import RandomForestClassifier
import joblib
import os

class CropRecommendationSystem:
    def __init__(self):
        self.model = None
        self.label_encoder = None
        self.scaler = None
        self.feature_columns = ['N', 'P', 'K', 'temperature', 'humidity', 'ph', 'rainfall']
        self.crop_economic_data = {
            'rice': {'base_profit': 18, 'min_temp': 20, 'max_temp': 35, 'min_rainfall': 100, 'max_rainfall': 300},
            'wheat': {'base_profit': 15, 'min_temp': 15, 'max_temp': 25, 'min_rainfall': 50, 'max_rainfall': 150},
            'cotton': {'base_profit': 22, 'min_temp': 18, 'max_temp': 32, 'min_rainfall': 60, 'max_rainfall': 200},
            'sugarcane': {'base_profit': 20, 'min_temp': 21, 'max_temp': 38, 'min_rainfall': 150, 'max_rainfall': 400},
            'maize': {'base_profit': 16, 'min_temp': 18, 'max_temp': 30, 'min_rainfall': 80, 'max_rainfall': 250},
            'jute': {'base_profit': 12, 'min_temp': 24, 'max_temp': 37, 'min_rainfall': 120, 'max_rainfall': 300},
            'coffee': {'base_profit': 25, 'min_temp': 15, 'max_temp': 28, 'min_rainfall': 150, 'max_rainfall': 300},
            'coconut': {'base_profit': 14, 'min_temp': 27, 'max_temp': 35, 'min_rainfall': 100, 'max_rainfall': 250},
            'apple': {'base_profit': 28, 'min_temp': 10, 'max_temp': 25, 'min_rainfall': 80, 'max_rainfall': 200},
            'banana': {'base_profit': 24, 'min_temp': 26, 'max_temp': 35, 'min_rainfall': 100, 'max_rainfall': 300},
            'blackgram': {'base_profit': 13, 'min_temp': 25, 'max_temp': 35, 'min_rainfall': 60, 'max_rainfall': 150},
            'chickpea': {'base_profit': 17, 'min_temp': 20, 'max_temp': 30, 'min_rainfall': 40, 'max_rainfall': 100},
            'grapes': {'base_profit': 30, 'min_temp': 15, 'max_temp': 30, 'min_rainfall': 50, 'max_rainfall': 150},
            'kidneybeans': {'base_profit': 15, 'min_temp': 15, 'max_temp': 25, 'min_rainfall': 60, 'max_rainfall': 120},
            'lentil': {'base_profit': 14, 'min_temp': 18, 'max_temp': 30, 'min_rainfall': 50, 'max_rainfall': 100},
            'mango': {'base_profit': 26, 'min_temp': 24, 'max_temp': 35, 'min_rainfall': 75, 'max_rainfall': 250},
            'mothbeans': {'base_profit': 11, 'min_temp': 25, 'max_temp': 35, 'min_rainfall': 40, 'max_rainfall': 80},
            'mungbean': {'base_profit': 13, 'min_temp': 25, 'max_temp': 35, 'min_rainfall': 60, 'max_rainfall': 120},
            'muskmelon': {'base_profit': 19, 'min_temp': 25, 'max_temp': 35, 'min_rainfall': 50, 'max_rainfall': 100},
            'orange': {'base_profit': 23, 'min_temp': 15, 'max_temp': 30, 'min_rainfall': 100, 'max_rainfall': 200},
            'papaya': {'base_profit': 21, 'min_temp': 25, 'max_temp': 35, 'min_rainfall': 100, 'max_rainfall': 200},
            'pigeonpeas': {'base_profit': 12, 'min_temp': 20, 'max_temp': 35, 'min_rainfall': 60, 'max_rainfall': 150},
            'pomegranate': {'base_profit': 27, 'min_temp': 15, 'max_temp': 35, 'min_rainfall': 50, 'max_rainfall': 150},
            'watermelon': {'base_profit': 18, 'min_temp': 25, 'max_temp': 35, 'min_rainfall': 50, 'max_rainfall': 100}
        }

    def load_models(self, model_path='adaptive_crop_recommender_model.pkl',
                   encoder_path='label_encoder.pkl', scaler_path='scaler.pkl'):
        """Load pre-trained models"""
        try:
            self.model = joblib.load(model_path)
            self.label_encoder = joblib.load(encoder_path)
            self.scaler = joblib.load(scaler_path)
            print("✅ Models loaded successfully!")
            return True
        except Exception as e:
            print(f"❌ Error loading models: {e}")
            return False

    def validate_input(self, sensor_data):
        """Validate sensor data input"""
        required_fields = self.feature_columns
        missing_fields = [field for field in required_fields if field not in sensor_data]

        if missing_fields:
            raise ValueError(f"Missing required fields: {missing_fields}")

        # Validate ranges
        validations = {
            'N': (0, 200), 'P': (0, 100), 'K': (0, 100),
            'temperature': (-10, 50), 'humidity': (0, 100),
            'ph': (0, 14), 'rainfall': (0, 500)
        }

        for field, (min_val, max_val) in validations.items():
            if not (min_val <= sensor_data[field] <= max_val):
                print(f"⚠️  Warning: {field} value {sensor_data[field]} is outside typical range ({min_val}-{max_val})")

    def calculate_economic_impact(self, crop_name, confidence_score, region_factor=1.0):
        """Calculate economic impact for a crop"""
        crop_data = self.crop_economic_data.get(crop_name.lower(), {'base_profit': 10})
        base_profit = crop_data['base_profit']

        # Adjust based on confidence and region
        confidence_multiplier = confidence_score / 100
        adjusted_profit = base_profit * confidence_multiplier * region_factor

        # Determine risk and recommendation
        if confidence_score >= 85:
            risk_level = "Very Low"
            recommendation = "Highly Recommended"
        elif confidence_score >= 70:
            risk_level = "Low"
            recommendation = "Recommended"
        elif confidence_score >= 55:
            risk_level = "Medium"
            recommendation = "Consider with Caution"
        else:
            risk_level = "High"
            recommendation = "Not Recommended"

        return {
            'estimated_profit_increase': f"{adjusted_profit:.1f}%",
            'base_profit_potential': f"{base_profit}%",
            'risk_level': risk_level,
            'investment_recommendation': recommendation,
            'confidence_score': f"{confidence_score:.1f}%"
        }

    def predict_crop_with_confidence(self, sensor_data, top_n=3):
        """Predict crop with confidence scores"""
        if not all([self.model, self.label_encoder, self.scaler]):
            raise ValueError("Models not loaded. Please load models first.")

        # Validate input
        self.validate_input(sensor_data)

        # Prepare input
        input_df = pd.DataFrame([sensor_data])
        input_df = input_df[self.feature_columns]  # Ensure correct order
        input_scaled = self.scaler.transform(input_df)

        # Get predictions and probabilities
        prediction = self.model.predict(input_scaled)
        probabilities = self.model.predict_proba(input_scaled)[0]

        # Get top N recommendations
        top_indices = np.argsort(probabilities)[::-1][:top_n]
        recommendations = []

        for idx in top_indices:
            crop_name = self.label_encoder.inverse_transform([idx])[0]
            confidence = probabilities[idx] * 100
            economic_impact = self.calculate_economic_impact(crop_name, confidence)

            recommendations.append({
                'crop': crop_name,
                'confidence': confidence,
                'economic_impact': economic_impact
            })

        return {
            'primary_recommendation': self.label_encoder.inverse_transform(prediction)[0],
            'top_recommendations': recommendations,
            'sensor_data': sensor_data
        }

    def get_unique_recommendations(self, sensor_data_list):
        """Get unique crop recommendations for multiple inputs"""
        all_recommendations = []
        used_crops = set()

        for i, sensor_data in enumerate(sensor_data_list):
            result = self.predict_crop_with_confidence(sensor_data, top_n=5)

            # Find best unique crop
            unique_crop = None
            for rec in result['top_recommendations']:
                if rec['crop'] not in used_crops:
                    unique_crop = rec
                    used_crops.add(rec['crop'])
                    break

            if unique_crop:
                all_recommendations.append({
                    'input_id': i + 1,
                    'sensor_data': sensor_data,
                    'recommended_crop': unique_crop['crop'],
                    'confidence': unique_crop['confidence'],
                    'economic_impact': unique_crop['economic_impact']
                })
            else:
                # Fallback to best available
                best_rec = result['top_recommendations'][0]
                all_recommendations.append({
                    'input_id': i + 1,
                    'sensor_data': sensor_data,
                    'recommended_crop': f"{best_rec['crop']} (duplicate)",
                    'confidence': best_rec['confidence'],
                    'economic_impact': best_rec['economic_impact']
                })

        return all_recommendations

def get_user_input():
    """Get sensor data from user input"""
    print("\n" + "="*50)
    print("🌱 CROP RECOMMENDATION SYSTEM")
    print("="*50)
    print("Enter sensor data values:")

    sensor_data = {}
    field_descriptions = {
        'N': 'Nitrogen (mg/kg) [0-200]',
        'P': 'Phosphorus (mg/kg) [0-100]',
        'K': 'Potassium (mg/kg) [0-100]',
        'temperature': 'Temperature (°C) [-10 to 50]',
        'humidity': 'Humidity (%) [0-100]',
        'ph': 'pH Level [0-14]',
        'rainfall': 'Rainfall (mm) [0-500]'
    }

    for field, description in field_descriptions.items():
        while True:
            try:
                value = float(input(f"{description}: "))
                sensor_data[field] = value
                break
            except ValueError:
                print("Please enter a valid number.")

    return sensor_data

def main():
    # Initialize system
    crop_system = CropRecommendationSystem()

    # Load models (make sure model files exist)
    if not crop_system.load_models():
        print("Please ensure model files exist in the current directory.")
        return

    while True:
        print("\n" + "="*50)
        print("🌾 CROP RECOMMENDATION OPTIONS")
        print("="*50)
        print("1. Single Crop Recommendation")
        print("2. Multiple Input Recommendations")
        print("3. Use Example Data")
        print("4. Exit")

        choice = input("\nSelect option (1-4): ").strip()

        if choice == '1':
            # Single recommendation
            sensor_data = get_user_input()
            try:
                result = crop_system.predict_crop_with_confidence(sensor_data)

                print("\n" + "="*50)
                print("🎯 CROP RECOMMENDATION RESULTS")
                print("="*50)
                print(f"Primary Recommendation: {result['primary_recommendation']}")

                print(f"\nTop {len(result['top_recommendations'])} Recommendations:")
                for i, rec in enumerate(result['top_recommendations'], 1):
                    econ = rec['economic_impact']
                    print(f"\n{i}. {rec['crop'].upper()}")
                    print(f"   Confidence: {rec['confidence']:.1f}%")
                    print(f"   Economic Impact: {econ['estimated_profit_increase']}")
                    print(f"   Risk Level: {econ['risk_level']}")
                    print(f"   Recommendation: {econ['investment_recommendation']}")

            except Exception as e:
                print(f"❌ Error: {e}")

        elif choice == '2':
            # Multiple recommendations
            num_inputs = int(input("How many sensor inputs? "))
            sensor_data_list = []

            for i in range(num_inputs):
                print(f"\n--- Input {i+1} ---")
                sensor_data = get_user_input()
                sensor_data_list.append(sensor_data)

            try:
                unique_recs = crop_system.get_unique_recommendations(sensor_data_list)

                print("\n" + "="*60)
                print("🎯 UNIQUE CROP RECOMMENDATIONS")
                print("="*60)

                for rec in unique_recs:
                    econ = rec['economic_impact']
                    print(f"\nInput {rec['input_id']}:")
                    print(f"Recommended Crop: {rec['recommended_crop']}")
                    print(f"Confidence: {rec['confidence']:.1f}%")
                    print(f"Economic Impact: {econ['estimated_profit_increase']}")
                    print(f"Risk Level: {econ['risk_level']}")
                    print(f"Investment Status: {econ['investment_recommendation']}")

            except Exception as e:
                print(f"❌ Error: {e}")

        elif choice == '3':
            # Example data
            example_data = [
                {'N': 90, 'P': 42, 'K': 43, 'temperature': 25.5, 'humidity': 70, 'ph': 6.8, 'rainfall': 150},
                {'N': 120, 'P': 60, 'K': 50, 'temperature': 22.0, 'humidity': 65, 'ph': 7.2, 'rainfall': 80},
                {'N': 80, 'P': 35, 'K': 40, 'temperature': 28.0, 'humidity': 75, 'ph': 6.5, 'rainfall': 200}
            ]

            print("\n🧪 Using Example Data:")
            for i, data in enumerate(example_data, 1):
                print(f"Example {i}: {data}")

            try:
                unique_recs = crop_system.get_unique_recommendations(example_data)

                print("\n" + "="*60)
                print("🎯 EXAMPLE RECOMMENDATIONS")
                print("="*60)

                for rec in unique_recs:
                    econ = rec['economic_impact']
                    print(f"\nExample {rec['input_id']}:")
                    print(f"Sensor Data: {rec['sensor_data']}")
                    print(f"Recommended Crop: {rec['recommended_crop']}")
                    print(f"Confidence: {rec['confidence']:.1f}%")
                    print(f"Economic Impact: {econ['estimated_profit_increase']}")
                    print(f"Risk Level: {econ['risk_level']}")
                    print(f"Investment Status: {econ['investment_recommendation']}")

            except Exception as e:
                print(f"❌ Error: {e}")

        elif choice == '4':
            print("👋 Thank you for using Crop Recommendation System!")
            break

        else:
            print("❌ Invalid choice. Please select 1-4.")

if __name__ == "__main__":
    main()

5